# Generated by Django 4.0.6 on 2024-10-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bomdata', '0002_maincomponent_alter_component_bom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='main_component',
        ),
        migrations.AlterField(
            model_name='component',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bomdata.bom'),
        ),
        migrations.DeleteModel(
            name='MainComponent',
        ),
    ]
