# Generated by Django 4.0.6 on 2024-10-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomdata', '0006_specification_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='objective',
            field=models.TextField(max_length=255),
        ),
    ]
