# Generated by Django 4.0.6 on 2024-10-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomdata', '0010_alter_specification_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='work_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
