# Generated by Django 4.0.6 on 2024-10-19 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bomdata', '0011_bom_work_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_components', to='bomdata.bom')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bomdata.component')),
            ],
        ),
    ]
