# Generated by Django 4.0.6 on 2024-10-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomdata', '0016_alter_specification_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='specification',
            field=models.CharField(max_length=500),
        ),
    ]
